# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agnostikos < Formula
  desc "Meta-wrapper package manager for Pacman, Nix, and Flatpak"
  homepage "https://github.com/ElioNeto/agnostikos"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/ElioNeto/agnostikos/releases/download/v0.1.0/agnostikos_0.1.0_linux_amd64.tar.gz"
    sha256 "ca4579055c3b5162ddc3fcb1a60e32a51a3ac36eab334de586b48dbd522cad0d"
    define_method(:install) do
      bin.install "agnostic"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ElioNeto/agnostikos/releases/download/v0.1.0/agnostikos_0.1.0_linux_arm64.tar.gz"
    sha256 "101a81e79904c33d9046fe724fc1cb1b2aaf4a893c0433cacf52b8faf344c0a3"
    define_method(:install) do
      bin.install "agnostic"
    end
  end
end
